// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWKGbmSGukqguDZ-M3ekgIBpcC2jqbBcU',
    appId: '1:940828423058:web:3006e1e124379ea515c74b',
    messagingSenderId: '940828423058',
    projectId: 'runearn',
    authDomain: 'runearn-24316.firebaseapp.com',
    storageBucket: 'runearn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBND7GzjdxOQcYWPW8GO0aVrgIK5SVkCU0',
    appId: '1:940828423058:android:dde779b752ad9bb315c74b',
    messagingSenderId: '940828423058',
    projectId: 'runearn',
    storageBucket: 'runearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Tu7NbtKNcUEzG-FLv_erg-sRK1oBFkc',
    appId: '1:940828423058:ios:32316bcd91e457c215c74b',
    messagingSenderId: '940828423058',
    projectId: 'runearn',
    storageBucket: 'runearn.firebasestorage.app',
    iosBundleId: 'com.jhaltolab.runearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWKGbmSGukqguDZ-M3ekgIBpcC2jqbBcU',
    appId: '1:940828423058:web:13044e10db3df10f15c74b',
    messagingSenderId: '940828423058',
    projectId: 'runearn',
    authDomain: 'runearn-24316.firebaseapp.com',
    storageBucket: 'runearn.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Tu7NbtKNcUEzG-FLv_erg-sRK1oBFkc',
    appId: '1:940828423058:ios:32316bcd91e457c215c74b',
    messagingSenderId: '940828423058',
    projectId: 'runearn',
    storageBucket: 'runearn.firebasestorage.app',
    iosBundleId: 'com.jhaltolab.runearn',
  );

}